### ISSUE TITLE
Grenades are worth very little

### ISSUE THREAD

**Issue by TheRealNin** [TheRealNin/NS2Combat#10]
Right now buying grenades is a pretty good way of throwing your points away. They deal relatively little damage and are gone once used until you respawn. If you want a pulse grenade effect, the recharging EMP blast is the way to go.

**Ideas to fix this:**
- Spawn with 2 grenades
- Resupply grenades every 25 seconds
- Resupply grenades on a kill
- Resupply grenades when you reach a new level

**Comment by GhoulofGSG9** [comment]
Getting a new grenade after each kill could be too strong with the pulse grenade. Also spawning with 2 gas grenades could be too strong as a single marine would be able to cover a complete room with gas that way.

**Comment by TheRealNin** [comment]
Resupply grenades and mines at the armory?

**Comment by DalinSeivewright** [comment]
In NS1 protecting/keeping the armory alive was a priority most of the time.  Allowed you to get the upperhand without wasting a point on ressuply.  Currently, the armory is not as important.  Allowing resupply only at the armory would make things exciting again.

**Comment by TheRealNin** [comment]
Perhaps with a cap of 2-3 mines per person, resupplying them at the armory wouldn't be so bad.

**Comment by TheRealNin** [comment]
I added the ability to resupply mines and grenades at armories.
